# Generated by Django 5.0.7 on 2024-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
