# Generated by Django 5.0.7 on 2024-09-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_rename_first_name_customuser_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=30),
        ),
    ]
