# Generated by Django 5.0.7 on 2024-09-04 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_customuser_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
