# Generated by Django 5.0.7 on 2024-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_rename_firstname_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
