# Generated by Django 5.0.7 on 2024-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=20)),
                ("text", models.CharField(max_length=200)),
                ("reciever", models.CharField(max_length=20)),
            ],
        ),
    ]
